@url_dev = http://localhost:3052/api/v1

### signup
POST {{url_dev}}/kata/signup
Content-Type: application/json

{
    "name": "Nguyen Quoc Thinh",
    "email": "thinhb2106815@student.ctu.edu.vn",
    "password": "fghj6789"
}

###signin
POST {{url_dev}}/kata/signin
Content-Type: application/json

# {
#     "email": "quickthink@gmail.com",
#     "password": "fghj6789"
# }

{
    "email": "thinhb2106815@student.ctu.edu.vn",
    "password": "fghj6789"
}


### reset password
POST {{url_dev}}/kata/reset-password/kasdjfk
Content-Type: application/json

{
    "password": "abcd1234"
}

### updateMe
PATCH {{url_dev}}/user/updateMe
Content-Type: application/json
BearerToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmMyMjQ3MWM4NjdkNWM3MWNiZTZhZjYiLCJyb2xlIjoidXNlciIsImlhdCI6MTcyNDA4NjkxOCwiZXhwIjoxNzI0MjU5NzE4fQ.w5XkqU85CyoE_Y0j52KeTjNcDRT9FCmDZPkgmXbY9l4

{
    "name": "Quoc Thinh"
}